CREATE DATABASE task2;
USE task2;
CREATE TABLE CHOCOLATE(sl_no int); 
  ALTER TABLE CHOCOLATE ADD COLUMN color varchar(5);
  ALTER TABLE CHOCOLATE ADD COLUMN name varchar(20);
  ALTER TABLE CHOCOLATE ADD COLUMN brand varchar(10);
  ALTER TABLE CHOCOLATE ADD COLUMN type varchar(50);
  ALTER TABLE CHOCOLATE ADD COLUMN flavor varchar(10);
  ALTER TABLE CHOCOLATE ADD COLUMN origin varchar(40);
  ALTER TABLE CHOCOLATE ADD COLUMN ingredients varchar(50);
  ALTER TABLE CHOCOLATE ADD COLUMN price decimal;
  ALTER TABLE CHOCOLATE ADD COLUMN weight decimal;
  ALTER TABLE CHOCOLATE ADD COLUMN expiry_date date;
  desc CHOCOLATE;
  ALTER TABLE CHOCOLATE DROP COLUMN expiry_date ;
  ALTER TABLE CHOCOLATE DROP COLUMN weight ;
  ALTER TABLE CHOCOLATE MODIFY  COLUMN price int;
  ALTER TABLE CHOCOLATE MODIFY  COLUMN ingredients double;
  ALTER TABLE CHOCOLATE MODIFY  COLUMN color float;
  ALTER TABLE CHOCOLATE RENAME COLUMN origin TO new_origin;
  ALTER TABLE CHOCOLATE RENAME COLUMN flavor TO taste;
  ALTER TABLE CHOCOLATE RENAME COLUMN type TO p_type;
  ALTER TABLE CHOCOLATE RENAME COLUMN name TO c_name;
  ALTER TABLE CHOCOLATE RENAME COLUMN brand TO brand_name;
  
  
  
CREATE TABLE COOKIES(sl_no int); 
  ALTER TABLE COOKIES ADD COLUMN color varchar(5);
  ALTER TABLE COOKIES ADD COLUMN name varchar(20);
  ALTER TABLE COOKIES ADD COLUMN brand varchar(10);
  ALTER TABLE COOKIES ADD COLUMN type varchar(50);
  ALTER TABLE COOKIES ADD COLUMN flavor varchar(10);
  ALTER TABLE COOKIES ADD COLUMN origin varchar(40);
  ALTER TABLE COOKIES ADD COLUMN ingredients varchar(50);
  ALTER TABLE COOKIES ADD COLUMN price decimal;
  ALTER TABLE COOKIES ADD COLUMN weight decimal;
  ALTER TABLE COOKIES ADD COLUMN expiry_date date;
  desc COOKIES;
  ALTER TABLE COOKIES DROP COLUMN expiry_date ;
  ALTER TABLE COOKIES DROP COLUMN weight ;
  ALTER TABLE COOKIES MODIFY  COLUMN price int;
  ALTER TABLE COOKIES MODIFY  COLUMN ingredients double;
  ALTER TABLE COOKIES MODIFY  COLUMN color float;
  ALTER TABLE COOKIES RENAME COLUMN origin TO new_origin;
  ALTER TABLE COOKIES RENAME COLUMN flavor TO taste;
  ALTER TABLE COOKIES RENAME COLUMN type TO p_type;
  ALTER TABLE COOKIES RENAME COLUMN name TO c_name;
  ALTER TABLE COOKIES RENAME COLUMN brand TO brand_name;
  
  
  
  CREATE TABLE ICE_CREAM(sl_no int); 
  ALTER TABLE ICE_CREAM ADD COLUMN color varchar(5);
  ALTER TABLE ICE_CREAM ADD COLUMN name varchar(20);
  ALTER TABLE ICE_CREAM ADD COLUMN brand varchar(10);
  ALTER TABLE ICE_CREAM ADD COLUMN type varchar(50);
  ALTER TABLE ICE_CREAM ADD COLUMN flavor varchar(10);
  ALTER TABLE ICE_CREAM ADD COLUMN origin varchar(40);
  ALTER TABLE ICE_CREAM ADD COLUMN ingredients varchar(50);
  ALTER TABLE ICE_CREAM ADD COLUMN price decimal;
  ALTER TABLE ICE_CREAM ADD COLUMN weight decimal;
  ALTER TABLE ICE_CREAM ADD COLUMN expiry_date date;
  desc ICE_CREAM;
  ALTER TABLE ICE_CREAM DROP COLUMN expiry_date ;
  ALTER TABLE ICE_CREAM DROP COLUMN weight ;
  ALTER TABLE ICE_CREAM MODIFY  COLUMN price int;
  ALTER TABLE ICE_CREAM MODIFY  COLUMN ingredients double;
  ALTER TABLE ICE_CREAM MODIFY  COLUMN color float;
  ALTER TABLE ICE_CREAM RENAME COLUMN origin TO new_origin;
  ALTER TABLE ICE_CREAM RENAME COLUMN flavor TO taste;
  ALTER TABLE ICE_CREAM RENAME COLUMN type TO p_type;
  ALTER TABLE ICE_CREAM RENAME COLUMN name TO c_name;
  ALTER TABLE ICE_CREAM RENAME COLUMN brand TO brand_name;
  

  
  CREATE TABLE FRUITS(sl_no int); 
  ALTER TABLE FRUITS ADD COLUMN color varchar(5);
  ALTER TABLE FRUITS ADD COLUMN name varchar(20);
  ALTER TABLE FRUITS ADD COLUMN brand varchar(10);
  ALTER TABLE FRUITS ADD COLUMN type varchar(50);
  ALTER TABLE FRUITS ADD COLUMN flavor varchar(10);
  ALTER TABLE FRUITS ADD COLUMN origin varchar(40);
  ALTER TABLE FRUITS ADD COLUMN manufacture_date date;
  ALTER TABLE FRUITS ADD COLUMN price decimal;
  ALTER TABLE FRUITS ADD COLUMN weight decimal;
  ALTER TABLE FRUITS ADD COLUMN expiry_date date;
  desc FRUITS;
  ALTER TABLE FRUITS DROP COLUMN expiry_date ;
  ALTER TABLE FRUITS DROP COLUMN weight ;
  ALTER TABLE FRUITS MODIFY  COLUMN price int;
  ALTER TABLE FRUITS MODIFY  COLUMN manufacture_date double;
  ALTER TABLE FRUITS MODIFY  COLUMN color float;
  ALTER TABLE FRUITS RENAME COLUMN origin TO new_origin;
  ALTER TABLE FRUITS RENAME COLUMN flavor TO taste;
  ALTER TABLE FRUITS RENAME COLUMN type TO p_type;
  ALTER TABLE FRUITS RENAME COLUMN name TO c_name;
  ALTER TABLE FRUITS RENAME COLUMN brand TO brand_name;
  
  
  
  CREATE TABLE WINDOWS(sl_no int); 
  ALTER TABLE WINDOWS ADD COLUMN color varchar(5);
  ALTER TABLE WINDOWS ADD COLUMN name varchar(20);
  ALTER TABLE WINDOWS ADD COLUMN brand varchar(10);
  ALTER TABLE WINDOWS ADD COLUMN type varchar(50);
  ALTER TABLE WINDOWS ADD COLUMN material varchar(10);
  ALTER TABLE WINDOWS ADD COLUMN glasstype varchar(40);
  ALTER TABLE WINDOWS ADD COLUMN size varchar(50);
  ALTER TABLE WINDOWS ADD COLUMN price decimal;
  ALTER TABLE WINDOWS ADD COLUMN weight decimal;
  ALTER TABLE WINDOWS ADD COLUMN openingtype varchar(20);
  desc WINDOWS;
  ALTER TABLE WINDOWS DROP COLUMN openingtype;
  ALTER TABLE WINDOWS DROP COLUMN weight;
  ALTER TABLE WINDOWS MODIFY COLUMN price int;
  ALTER TABLE WINDOWS MODIFY COLUMN size double;
  ALTER TABLE WINDOWS MODIFY COLUMN glasstype float;
  ALTER TABLE WINDOWS RENAME COLUMN material TO new_material;
  ALTER TABLE WINDOWS RENAME COLUMN type TO p_type;
  ALTER TABLE WINDOWS RENAME COLUMN brand TO brand_type;
  ALTER TABLE WINDOWS RENAME COLUMN name TO c_name;
  ALTER TABLE WINDOWS RENAME COLUMN color TO color_name;
  
  
  
  CREATE TABLE FAMILY(sl_no int); 
  ALTER TABLE FAMILY ADD COLUMN address varchar(5);
  ALTER TABLE FAMILY ADD COLUMN name varchar(20);
  ALTER TABLE FAMILY ADD COLUMN city varchar(10);
  ALTER TABLE FAMILY ADD COLUMN state varchar(50);
  ALTER TABLE FAMILY ADD COLUMN country varchar(10);
  ALTER TABLE FAMILY ADD COLUMN fathername varchar(40);
  ALTER TABLE FAMILY ADD COLUMN mothername varchar(40);
  ALTER TABLE FAMILY ADD COLUMN children int;
  ALTER TABLE FAMILY ADD COLUMN contactnumber varchar(40);
  ALTER TABLE FAMILY ADD COLUMN place varchar(40);
  desc FAMILY;
  ALTER TABLE FAMILY DROP COLUMN place ;
  ALTER TABLE FAMILY DROP COLUMN contactnumber ;
  ALTER TABLE FAMILY MODIFY  COLUMN children float;
  ALTER TABLE FAMILY MODIFY  COLUMN mothername double;
  ALTER TABLE FAMILY MODIFY  COLUMN fathername float;
  ALTER TABLE FAMILY RENAME COLUMN country TO new_country;
  ALTER TABLE FAMILY RENAME COLUMN state TO p_state;
  ALTER TABLE FAMILY RENAME COLUMN city TO q_city;
  ALTER TABLE FAMILY RENAME COLUMN name TO c_name;
  ALTER TABLE FAMILY RENAME COLUMN address TO address_name;
  
  
  
  CREATE TABLE AMBULANCE(sl_no int); 
  ALTER TABLE AMBULANCE ADD COLUMN color varchar(5);
  ALTER TABLE AMBULANCE ADD COLUMN vehiclenumber varchar(20);
  ALTER TABLE AMBULANCE ADD COLUMN model varchar(10);
  ALTER TABLE AMBULANCE ADD COLUMN manufacturer varchar(100);
  ALTER TABLE AMBULANCE ADD COLUMN type varchar(10);
  ALTER TABLE AMBULANCE ADD COLUMN capacity int;
  ALTER TABLE AMBULANCE ADD COLUMN status varchar(20);
  ALTER TABLE AMBULANCE ADD COLUMN location varchar(200);
  ALTER TABLE AMBULANCE ADD COLUMN weight decimal;
  ALTER TABLE AMBULANCE ADD COLUMN drivername varchar(100);
  desc AMBULANCE;
  ALTER TABLE AMBULANCE DROP COLUMN drivername ;
  ALTER TABLE AMBULANCE DROP COLUMN weight ;
  ALTER TABLE AMBULANCE MODIFY  COLUMN location int;
  ALTER TABLE AMBULANCE MODIFY  COLUMN status double;
  ALTER TABLE AMBULANCE MODIFY  COLUMN capacity float;
  ALTER TABLE AMBULANCE RENAME COLUMN type TO new_type;
  ALTER TABLE AMBULANCE RENAME COLUMN manufacturer TO p_manufacturer;
  ALTER TABLE AMBULANCE RENAME COLUMN model TO m_model;
  ALTER TABLE AMBULANCE RENAME COLUMN vehiclenumber TO v_vehiclenumber;
  ALTER TABLE AMBULANCE RENAME COLUMN color TO color_name;
  
  
  CREATE TABLE HOSPITAL(sl_no int); 
  ALTER TABLE HOSPITAL ADD COLUMN address varchar(5);
  ALTER TABLE HOSPITAL ADD COLUMN name varchar(20);
  ALTER TABLE HOSPITAL ADD COLUMN city varchar(10);
  ALTER TABLE HOSPITAL ADD COLUMN state varchar(50);
  ALTER TABLE HOSPITAL ADD COLUMN country varchar(10);
  ALTER TABLE HOSPITAL ADD COLUMN phone varchar(40);
  ALTER TABLE HOSPITAL ADD COLUMN email varchar(40);
  ALTER TABLE HOSPITAL ADD COLUMN bed int;
  ALTER TABLE HOSPITAL ADD COLUMN director varchar(40);
  ALTER TABLE HOSPITAL ADD COLUMN place varchar(40);
  desc HOSPITAL;
  ALTER TABLE HOSPITAL DROP COLUMN place ;
  ALTER TABLE HOSPITAL DROP COLUMN director ;
  ALTER TABLE HOSPITAL MODIFY  COLUMN bed float;
  ALTER TABLE HOSPITAL MODIFY  COLUMN email double;
  ALTER TABLE HOSPITAL MODIFY  COLUMN phone float;
  ALTER TABLE HOSPITAL RENAME COLUMN country TO new_country;
  ALTER TABLE HOSPITAL RENAME COLUMN state TO p_state;
  ALTER TABLE HOSPITAL RENAME COLUMN city TO q_city;
  ALTER TABLE HOSPITAL RENAME COLUMN name TO c_name;
  ALTER TABLE HOSPITAL RENAME COLUMN address TO address_name;
  
  
  
  CREATE TABLE BUS_STAND(sl_no int); 
  ALTER TABLE BUS_STAND ADD COLUMN address varchar(5);
  ALTER TABLE BUS_STAND ADD COLUMN name varchar(20);
  ALTER TABLE BUS_STAND ADD COLUMN city varchar(10);
  ALTER TABLE BUS_STAND ADD COLUMN state varchar(50);
  ALTER TABLE BUS_STAND ADD COLUMN country varchar(10);
  ALTER TABLE BUS_STAND ADD COLUMN contactnumber varchar(40);
  ALTER TABLE BUS_STAND ADD COLUMN facilities varchar(40);
  ALTER TABLE BUS_STAND ADD COLUMN latitude decimal;
  ALTER TABLE BUS_STAND ADD COLUMN longitude decimal;
  ALTER TABLE BUS_STAND ADD COLUMN location varchar(40);
  desc BUS_STAND;
  ALTER TABLE BUS_STAND DROP COLUMN location ;
  ALTER TABLE BUS_STAND DROP COLUMN longitude ;
  ALTER TABLE BUS_STAND MODIFY  COLUMN latitude float;
  ALTER TABLE BUS_STAND MODIFY  COLUMN facilities double;
  ALTER TABLE BUS_STAND MODIFY  COLUMN contactnumber float;
  ALTER TABLE BUS_STAND RENAME COLUMN country TO new_country;
  ALTER TABLE BUS_STAND RENAME COLUMN state TO p_state;
  ALTER TABLE BUS_STAND RENAME COLUMN city TO q_city;
  ALTER TABLE BUS_STAND RENAME COLUMN name TO c_name;
  ALTER TABLE BUS_STAND RENAME COLUMN address TO address_name;
  
  
  
CREATE TABLE MATCH_BOX(sl_no int); 
  ALTER TABLE MATCH_BOX ADD COLUMN brand varchar(5);
  ALTER TABLE MATCH_BOX ADD COLUMN size varchar(20);
  ALTER TABLE MATCH_BOX ADD COLUMN material varchar(10);
  ALTER TABLE MATCH_BOX ADD COLUMN color varchar(50);
  ALTER TABLE MATCH_BOX ADD COLUMN stickertype varchar(10);
  ALTER TABLE MATCH_BOX ADD COLUMN quantity int;
  ALTER TABLE MATCH_BOX ADD COLUMN design varchar(40);
  ALTER TABLE MATCH_BOX ADD COLUMN price decimal;
  ALTER TABLE MATCH_BOX ADD COLUMN productiondate date;
  ALTER TABLE MATCH_BOX ADD COLUMN manufacturer varchar(40);
  desc MATCH_BOX;
  ALTER TABLE MATCH_BOX DROP COLUMN manufacturer ;
  ALTER TABLE MATCH_BOX DROP COLUMN productiondate ;
  ALTER TABLE MATCH_BOX MODIFY  COLUMN price float;
  ALTER TABLE MATCH_BOX MODIFY  COLUMN design double;
  ALTER TABLE MATCH_BOX MODIFY  COLUMN quantity float;
  ALTER TABLE MATCH_BOX RENAME COLUMN stickertype TO s_stickertype;
  ALTER TABLE MATCH_BOX RENAME COLUMN color TO color_name;
  ALTER TABLE MATCH_BOX RENAME COLUMN material TO m_material;
  ALTER TABLE MATCH_BOX RENAME COLUMN size TO size_small;
  ALTER TABLE MATCH_BOX RENAME COLUMN brand TO new_brand;
  

  

  
